apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanak81-mtnblog12345
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/thanak81-mtnblog12345.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: thanak81-mtnblog12345
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
