apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanak81-mtnblog12345-certificate
  namespace: thanak81-mtnblog12345
spec:
  secretName: thanak81-mtnblog12345-secret-tls
  commonName: thanak81-mtnblog12345.assessify.org
  dnsNames:
  - thanak81-mtnblog12345.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
